### ISSUE TITLE
Can I pass variables into different fragment of components

### ISSUE THREAD

**Issue by JimmyLv** [smooth-code/fraql#10]
This library is awesome, and I met a use case which are about the apollo variables.

I have more than two `productByCode` fragments inside different components, 

eg: 

```
fragment on Query { 
  shop {
    one: productByCode(codes: $codes) {
      id
      code
      title
      image
 	  price {
        amount
        currencyCode
      }
    }
  }
```

```
fragment on Query { 
  shop {
    two: productByCode(codes: $codes) {
      id
      badge
      image
    }
  }
```

How can inject the `$codes` variables from the top, which can be got by different fragments.

**Comment by neoziro** [comment]
Variables cannot be passed to fragments, it is a GraphQL limitation sorry.
